# Generated by Django 4.1.2 on 2022-11-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_rename_stores_table'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='store_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
            preserve_default=False,
        ),
    ]
