# Generated by Django 4.1.2 on 2023-02-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('orders', '0001_initial'),
        ('components', '0002_categories_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='Components',
        ),
    ]
