# Generated by Django 4.1.2 on 2022-11-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_rename_store_id_component_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='display_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
