# Generated by Django 4.1.2 on 2022-11-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_categories_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='display_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
