# Generated by Django 4.1.2 on 2022-12-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_categories_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='stores',
            new_name='store_id',
        ),
    ]
