# Generated by Django 4.1.2 on 2022-11-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_add_stores_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Stores',
        ),
    ]
